### ISSUE TITLE
Pulling data from a custom PID found through torque pro

### ISSUE THREAD

**Issue by Blackbeard25** [PowerBroker2/ELMduino#170]
I'm trying to figure out a way to use a PID defined in torque pro. I really don't have any idea where to start. This is the PID definition from torque:
```
"Name", "ShortName", "ModeAndPID", "Equation", "Min Value", "Max Value", "Units", "Header", "startDiagnostic", "stopDiagnostic", "scale","minimumRefreshDelayMillis"
"[FORD]Boost (Ford specific)","MAP","0x221440","(((A*256)+B)*0.03625)-BARO()",0,30,"psi","Auto","","",1,0
```
If someone could point me in the right direction/generate the code needed to put the data into a variable that would be great thanks

**Comment by patfelst** [comment]
I can help with this as I’ve coded a complete boost gauge with peak hold. If you can wait until the weekend I’ll post a code snippet.

**Comment by Blackbeard25** [comment]
for sure. I don't need the peak hold or nothing, just how to use this information to have a working boost gauge. Really hopefully going to be a place for me to start with for my digital dash project. I guess I should add that I will be using the J1850-PWM protocol

**Comment by patfelst** [comment]
Basically you need to query the manifold absolute pressure PID (0x0B), and also barometric pressure PID (0x33), then subtract barometric pressure from manifold pressure. If the result is positive, the turbo is creating boost, if the result is negative, the manifold is in vaccum (foot is off the accelerator / engine coasting). 
The two PIDs you need are:
```c++
const uint8_t INTAKE_MANIFOLD_ABS_PRESSURE     = 11;  // 0x0B - kPa
const uint8_t ABS_BAROMETRIC_PRESSURE          = 51;  // 0x33 - kPa
```
First of all can you check if you can query the above two PIDs?

Then to calculate boost, create a singed variable because, as per above, boost can be  positive (boost) or negative (vacuum):
```c++
  // You need to query the PIDs using the non-blocking loop code shown in the multiple PIDs example
  uint8_t = intake_pressure_kpa = ELM327.manifoldPressure();
  uint8_t = baro_pressure_kpa = ELM327.absBaroPressure();

  // Now calculate boost in kpa
  int16_t boost_pressure_kpa = intake_pressure_kpa - baro_pressure_kpa; // Calculate boost pressure

  // And convert to psi
  float boost_pressure_psi = (float)boost_pressure_kpa * 0.1450377;
```

**Comment by patfelst** [comment]
@Blackbeard25 how did you go with this?
