### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by martindo72050** [PowerBroker2/ELMduino#41]
Hello. I'm sorry to open another issue on this topic, I've been trying to figure this out for a few days now and can't. Probably my inexperience. Anyway my hardware is:

- Arduino Mega
- HC05
- Bafx ELM327

I'm able to connect and retrieve data using AT commands, but I get timeout errors after connecting using the example code. Any ideas?

**Comment by PowerBroker2** [comment]
I've had timeouts occur, but only rarely. Are you able to get any data at all with the example before getting timeouts? What happens if you edit the CPP file to follow [this configuration](https://github.com/PowerBroker2/ELMduino/issues/40#issuecomment-667602916)?

**Comment by martindo72050** [comment]
No data before timeouts. I'll try that and let you know

**Comment by PowerBroker2** [comment]
You can use the macros from the header file, but I think you can do what you posted instead

**Comment by martindo72050** [comment]
Tried it and still get the same issue

**Comment by PowerBroker2** [comment]
You said you can get data using AT commands. Can you provide that list of AT commands and their responses?

**Comment by martindo72050** [comment]
Yes. I actually only used the AT commands for setting up the HC05, then I got it out of AT mode and started simply typing the PIDs. Here I repeatedly typed 010C (rpm) and got this response:
![Untitled drawing (7)](https://user-images.githubusercontent.com/68865574/89741177-1ce7fa00-da5d-11ea-8a85-7b1a03bcc069.png)

**Comment by PowerBroker2** [comment]
In that case, try getting rid of all AT commands in the `begin()` method and see if that fixes it

**Comment by martindo72050** [comment]
Same result. Here is my current Arduino code:
#include <ELMduino.h>

#include <SoftwareSerial.h>
#include "ELMduino.h"


//SoftwareSerial mySerial(10, 11); // RX, TX
#define ELM_PORT Serial1


ELM327 myELM327;


uint32_t rpm = 0;


void setup()
{
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, HIGH);

  Serial.begin(38400);
  ELM_PORT.begin(38400);

  Serial.println("Attempting to connect to ELM327...");

  if (!myELM327.begin(ELM_PORT))
  {
    Serial.println("Couldn't connect to OBD scanner");
    while (1);
  }

  Serial.println("Connected to ELM327");
}


void loop()
{
  float tempRPM = myELM327.rpm();

  if (myELM327.status == ELM_SUCCESS)
  {
    rpm = (uint32_t)tempRPM;
    Serial.print("RPM: "); Serial.println(rpm);
  }
  else
  {
    Serial.print(F("\tERROR: "));
    Serial.println(myELM327.status);
    delay(100);
  }  
  delay(1000);
}

**Comment by brainfoolong** [comment]
Hi, i also have the same problem. If looked into the elmduino code and i found something that i can't explain. Currently it is so: After successfull initialization, once you get a `ELM_TIMEOUT` or `ELM_UNABLE_TO_CONNECT` after any command, you are stuck in that status and can't send any other commands.

It's because in current code, the `connected` flag is set to false on the begin of every sendCommand -> https://github.com/PowerBroker2/ELMduino/blob/342fc1e581ecf44b829053a55a6a4aeaf6852b81/src/ELMduino.cpp#L508

This flag is only updated to true when you have received any success request (no timeout or unable to connect) -> https://github.com/PowerBroker2/ELMduino/blob/342fc1e581ecf44b829053a55a6a4aeaf6852b81/src/ELMduino.cpp#L554

And the problem with this is, every call to `queryPID`, which you basically use for every data you want, require a `connected = true` -> https://github.com/PowerBroker2/ELMduino/blob/342fc1e581ecf44b829053a55a6a4aeaf6852b81/src/ELMduino.cpp#L360

But this `connected ` will never be `true` again.

I've created a pull request, maybe this is helpful for someone and maybe this will be merged by the maintainer.

**Comment by PowerBroker2** [comment]
Oh dang, good catch! I'll take a look at the PR. I've had trouble with many users (including myself, actually) having this timeout error issue, but could never figure it out - I hope this bug is the root of the issue.

**Comment by PowerBroker2** [comment]
This should be resolved with release [2.3.2](https://github.com/PowerBroker2/ELMduino/releases/tag/2.3.2)
